CREATE TABLE produktet (
  id INT NOT NULL AUTO_INCREMENT,
  emri VARCHAR(255) NOT NULL,
  pershkrimi TEXT NOT NULL,
  foto_emri VARCHAR(255) NOT NULL,
  koha_e_shtimit TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);